name: "Continuous Integration"

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    tests:
        name: "CI ${{ matrix.operating-system }} / PHP ${{ matrix.php-version }}"
        runs-on: ${{ matrix.operating-system }}
        strategy:
            matrix:
                operating-system: ['ubuntu-latest', 'macos-latest']
                php-version: ['7.2.5', '7.3', '7.4', '8.0']

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v2"

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "${{ matrix.php-version }}"
                  tools: composer

            - name: Get composer cache directory
              id: composercache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composercache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Test PHPUnit
              run: ./vendor/bin/simple-phpunit

            - name: Test PHP-CS-Fixer
              run: ./vendor/bin/php-cs-fixer fix --dry-run --diff --no-ansi

            - name: Test PHPStan
              run: ./vendor/bin/phpstan analyse