name: "Continuous Integration"

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    tests:
        name: "CI PHP ${{ matrix.php-version }}"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: ['7.2.5', '7.3', '7.4', '8.0', '8.1']

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 2

            - name: Docker run container
              run: docker-compose -f .docker/docker-compose.yaml up -d

            - name: Wait for PresaShop container
              run: ./.github/workflows/scripts/docker-inspect.sh prestashop 180

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "${{ matrix.php-version }}"
                  tools: composer

            - name: Get composer cache directory
              id: composercache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composercache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress

            - name: Test PHP-CS-Fixer
              if: matrix.php-version != '8.1'
              run: ./vendor/bin/php-cs-fixer fix --dry-run --diff --no-ansi

            - name: Test PHPStan
              run: ./vendor/bin/phpstan analyse

            - name: Test PHPUnit
              run: ./vendor/bin/phpunit --coverage-clover=coverage.clover

            - name: Upload coverage to Scrutinizer
              run: |
                  composer global require scrutinizer/ocular
                  ~/.composer/vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
